### ISSUE TITLE
You're not authorized to access this page. Please contact the administrator.

### ISSUE THREAD

**Issue by JuanLottZA** [hkamel/sonar-auth-aad#100]
I configured the sonar-auth-aad plugin from the documentation provided in https://github.com/hkamel/sonar-auth-aad/wiki/Setup

Secondly I configured "Syncing Groups with Active Directory"
https://github.com/hkamel/sonar-auth-aad/wiki/Group-Sync

In SonarQube I then created a group with the same name of one that exists in AAD.

Once I completed all configurations I browsed SonarQube and used the "Log in with Microsoft" option to authenticate.

This takes me through the authentication process and once authenticated I'm redirect to a page that displays the following message "You're not authorized to access this page. Please contact the administrator."

Any help would be greatly appreciated.

**Comment by sewalshmsft** [comment]
Did you figure this out?

**Comment by JuanLottZA** [comment]
> Did you figure this out?
I did, please see screen shots below.

![image](https://user-images.githubusercontent.com/64904269/84427931-a57c2280-abf3-11ea-939f-6335a7923b5e.png)

In my scenario I had "User assignment required" set to yes and did not specify any users or groups. If this is set to "No" any user in the domain will be able to access the application.

To correct this you navigate to "Users and groups" and specify the users or groups that needs access.

![image](https://user-images.githubusercontent.com/64904269/84428343-48cd3780-abf4-11ea-91f1-f2c56d09a214.png)

**Comment by swapnil-nq** [comment]
I tried this but it won't work. same error occured.

**Comment by swapnil-nq** [comment]
> > Did you figure this out?
> > I did, please see screen shots below.
> 
> ![image](https://user-images.githubusercontent.com/64904269/84427931-a57c2280-abf3-11ea-939f-6335a7923b5e.png)
> 
> In my scenario I had "User assignment required" set to yes and did not specify any users or groups.
> 
> If this is set to "No" any user in the domain will be able to access the application.
> 
> To correct this I navigated to "Users and groups" and specified the groups that needed access.
> 
> ![image](https://user-images.githubusercontent.com/64904269/84428343-48cd3780-abf4-11ea-91f1-f2c56d09a214.png)

Its not working, still getting the same error.
