### ISSUE TITLE
Issue on enabling grant for azure graph as well as microsoft graph. 

### ISSUE THREAD

**Issue by brightysara2603** [hkamel/sonar-auth-aad#103]
We have configured this plugin for our sonar. After giving Directory.AccessAsUser.All to the microsoft graph as well as azure graph,  our AAD team is saying The risk presented by the permission is too high to enable, even on a test basis, without appropriate review from a security perspective. If enabled, the application can impersonate any user including their associated privilege, and for our admin users in particular this is a significant problem. What is the risk here? How can we mitigate this? Also how can we login as a user to sonarqube using this plugin not group sync?

**Comment by srvrguy** [comment]
You can absolutely use the plugin without the group sync functionality. The group sync feature is off by default. If you don't want to use that feature, you do not need to grant that permission.

The current permission listed in the documentation is probably way too much access for the needs of the plugin. It could allow an application with the access key to do any read or write action on the AAD, at least via the MS Graph API. I haven't had much time to validate a lower level access, but you could try the permission of "Directory.Read.All" and see if that will work. It's the least privileged permission that can read the endpoint used to get that information.

**Comment by Mobrockers** [comment]
@srvrguy We use Directory.Read.All and not Directory.AccessAsUser.All. Group sync works fine. You can probably just change the documentation.

**Comment by srvrguy** [comment]
This issue is old and hasn't had any activity. If the problem still exists, please open a new issue.
