### ISSUE TITLE
Plugin description links to sonarcloud

### ISSUE THREAD

**Issue by christophe-havard-sonarsource** [hkamel/sonar-auth-aad#104]
Hi guys,
Seems like the plugin description blade in the marketplace links to sonarcloud instead of sonarqube.
![image](https://user-images.githubusercontent.com/65390576/86456922-29bd5380-bd23-11ea-8ab0-97b0c8010e8d.png)

Kind regards,
Chris

**Comment by srvrguy** [comment]
That's not this plugin. That's a method to use SonarQube's built-in SAML integration.
