### ISSUE TITLE
Upgrade from ADAL to MSAL

### ISSUE THREAD

**Issue by andershermansen** [hkamel/sonar-auth-aad#107]
**Email from Microsoft:**

> Upgrade your applications to use Microsoft Authentication Library (MSAL). We’re no longer adding new features to Azure Active Directory Authentication Library (ADAL) and starting June 30th, 2022 we will no longer provide any technical support or security updates.  Instead we recommend you use MSAL, which is where we will continue to invest. MSAL makes it easy for you to build applications that authenticate users and acquire tokens to access resources.
> 
> You are receiving this message because our reporting indicates one or more of your applications are using ADAL. Applications using ADAL on existing OS versions will continue to work after June 30th, 2022 but will not receive any technical support or security updates.

**From ADAL4J github**
https://github.com/AzureAD/azure-activedirectory-library-for-java#update-to-msal4j-now

> Update to MSAL4J now!
> MSAL4J is the new authentication library to be used with the Microsoft identity platform.

**MSAL4J github**
https://github.com/AzureAD/microsoft-authentication-library-for-java

**Migration guide**
https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Migrate-to-MSAL-Java

**Comment by sushant-pradhan** [comment]
#120

**Comment by srvrguy** [comment]
As was noted, this is being tracked on #120
