### ISSUE TITLE
CVE critical vulnerability detected in json dependency

### ISSUE THREAD

**Issue by shubhangijadhav** [hkamel/sonar-auth-aad#114]
Hi,

    We have been successfully using the plugin for quite some time now, but recently our vulnerability scanner (aquasec) has detected a critical vulnerability in one of the dependencies, to be precise the following:
![image](https://user-images.githubusercontent.com/3209932/118626032-cf0dd880-b7ca-11eb-9783-f67910c7a7f1.png)

**Comment by srvrguy** [comment]
This was fixed in version 1.3.1 of this plugin when the version of adal4j was updated.
