### ISSUE TITLE
8.9 compatibility

### ISSUE THREAD

**Issue by ChapChap** [hkamel/sonar-auth-aad#115]
Hi @hkamel,

Is this module compatible or needed in sonarqube 8.9 ?

Regards,
Chap

**Comment by srvrguy** [comment]
I have not tested it yet (it's been a bit busy at work with other projects), but it _should_ work fine with 8.9. There is still no direct support for AAD in SonarQube, but you can use the SAML auth options with slightly different functionality.

**Comment by ChapChap** [comment]
It is 🙏
