### ISSUE TITLE
You're not authorized to access this page. Please contact the administrator.

### ISSUE THREAD

**Issue by swapnil-nq** [hkamel/sonar-auth-aad#116]
Setup azure aad and also setup in sonar qube done. but after login I'm getting "You're not authorized to access this page. Please contact the administrator." error.

Please help how need to be done in next steps.

**Comment by swapnil-nq** [comment]
![image](https://user-images.githubusercontent.com/87093187/124814841-1f601600-df84-11eb-8930-9471f5537270.png)

**Comment by thomas-edt** [comment]
i get too :/

**Comment by pchigulla** [comment]
I am receiving the same error. Currenty, my sonarqube is at 8.9.1 version. Is there an issue with the Azure AAD integration . I have followed all the steps from this blog https://www.emtec.digital/think-hub/blogs/sonarqube-integration-azure-active-directory/
Please suggest 
@hkamel

**Comment by vittoriocanilli** [comment]
I have set up the Azure AD Auth by following the wiki of the plugin: https://github.com/hkamel/sonar-auth-aad/wiki/Setup

I have then encountered the same problem, but I have managed to solve it after that in the SonarQube logs I have found this:
`[o.a.a.a.AadIdentityProvider] Exception:org.sonar.server.authentication.exception.EmailAlreadyExistsRedirectionException`

I had to remove the email address from the SonarQube user, which is not synched with AAD: the email address is not a required detail luckily. After that I was able to log in with my AAD user.

My setup is SonarQube 9.0.1 Community Edition and AAD plugin 1.2.0.
I hope it helps.

**Comment by srvrguy** [comment]
Please make sure to check the SQ logs and post any relevant lines from it. There are a few reasons that login can fail, and without seeing the log, it's impossible to know which reason it is. A few common ones:

- You have existing users on the SQ install and their login matches the old login. In this case, make sure the "Login Strategy" is set to "Unique".
- You have existing users on the SQ install and their e-mail matches the AAD login. In this case, change the e-mail on the old accounts.
- You have a setting in AAD or the SP you made in AAD that is preventing proper login. You need to check the SQ logs and possibly Azure logs to see what is going on.

Those are just the top three issues I can think of right now. Also, make sure your setup matches the one discussed in the Wiki here.

**Comment by wmeg-aprico** [comment]
@srvrguy 

I faced the same issue and I would like to share with you my experience. I wish this would help :)
In fact I configured the plugin I my SonarQube Server version Community EditionVersion 9.1 (build 47736). The plugin worked as expected.

I did the upgrade of the Server to the latest one. After this upgrade, the authentication using Azure AD is not working any more a n I get the same error "You're not authorized ...."

I did the downgrade, the plugin worked again.

Best Regards.

**Comment by barnesdc** [comment]
I had the same issue with my sonarqube instance and was resolved by adding microsoft graph api permissions. Maybe this should be added to the instructions.
<img width="1412" alt="Screen Shot 2022-08-29 at 3 38 52 PM" src="https://user-images.githubusercontent.com/22064007/187304292-c18f9076-d029-4c21-8f75-17b276020214.png">

**Comment by srvrguy** [comment]
@barnesdc Your permissions are different from those listed in the documentation. Here's what is used in production at my employer:
<img width="915" alt="Screen Shot 2022-10-21 at 11 11 25 AM" src="https://user-images.githubusercontent.com/1612403/197262073-4bf06dec-935e-4cde-9458-d4d0485a6a49.png">

It's currently running against the latest release of this plugin on SQ Community 9.6.1.

I believe the User.Read permission is automatically granted, and incorporates all the info needed for the basic SSO portion of the plugin. If MS has changed this behavior, I can update the documentation.

**Comment by barnesdc** [comment]
> @barnesdc Your permissions are different from those listed in the documentation. Here's what is used in production at my employer:
> 
> <img width="915" alt="Screen Shot 2022-10-21 at 11 11 25 AM" src="https://user-images.githubusercontent.com/1612403/197262073-4bf06dec-935e-4cde-9458-d4d0485a6a49.png">
> 
> 
> 
> It's currently running against the latest release of this plugin on SQ Community 9.6.1.
> 
> 
> 
> I believe the User.Read permission is automatically granted, and incorporates all the info needed for the basic SSO portion of the plugin. If MS has changed this behavior, I can update the documentation.

It could be that my organization looks everything down by default, so maybe I'm in one of those uncommon situations.

**Comment by srvrguy** [comment]
That is very possible. You only need the Directory permission for group sync (and if you're using the new sync method, there's a different permission as explained in the docs). Otherwise, User.Read is the basic catch-all for being able to grab the profile information this plugin uses without enumerating every single item, and this is the default permission configuration for new applications.

**Comment by barnesdc** [comment]
Ran into the same issue with another application... seems we dont grant access to those Directory permissions by default and typically only for very specific purposes.

**Comment by srvrguy** [comment]
I just tested setting up the app registration following the documented steps in the wiki. Even with just a basic registration and not going to any steps to grant permissions or adjust the authentication to include id tokens the app is still granted basic User.Read access on the application.

If this is not happening by default for others, there must be a reason for this. I'd really appreciate some details into what settings or setup method is being used that results in this permission not being added so I can specifically account for that in the setup instructions.

**Comment by srvrguy** [comment]
I think I found some information out that may be helpful.

If you follow the setup guide on this project and add the application via the Azure Portal, it gets automatically assigned the right permissions for basic sign-in. This is not the case if you create the application registration by other means such as Terraform. There's an example of how to do this over [here](https://registry.terraform.io/providers/hashicorp/azuread/1.5.0/docs/guides/microsoft-graph#behaviour-change-default-user_impersonation-scope-for-applications).

Just in case that link breaks in the future for those reading this report, here's a working example I use elsewhere for Terraform:

```
# Create a UUID for the Azure AD Application Impersonation Scope
resource "random_uuid" "sonarqube_user_impersonation_scope" {}

# App Registration
resource "azuread_application" "sonarqube" {
  display_name = "SonarQube"

  prevent_duplicate_names = true

  sign_in_audience = "AzureADMyOrg"

  web {
    homepage_url = "https://${var.site_url}/"

    redirect_uris = [
      "https://${var.site_url}/oauth2/callback/aad"
    ]

    implicit_grant {
      access_token_issuance_enabled = false
      id_token_issuance_enabled     = true
    }
  }

  api {
    oauth2_permission_scope {
      admin_consent_description  = "Allow the application to access sonarqube on behalf of the signed-in user."
      admin_consent_display_name = "Access sonarqube"
      enabled                    = true
      id                         = random_uuid.sonarqube_user_impersonation_scope.result
      type                       = "User"
      user_consent_description   = "Allow the application to access sonarqube on your behalf."
      user_consent_display_name  = "Access testing-sonarqube"
      value                      = "user_impersonation"
    }
  }

  required_resource_access {
    resource_app_id = "00000003-0000-0000-c000-000000000000" # Microsoft Graph API

    resource_access {
      id   = "e1fe6dd8-ba31-4d61-89e7-88639da4683d" # User.Read
      type = "Scope"
    }
  }
}
```

For group sync, you'll need to add the additional permissions required. Obviously, if you use a different system for creating the application registration you'll need to translate this into the system you use.
