### ISSUE TITLE
Sonar is redirecting to http://localhost:9000/sessions/unauthorized after AAD authentication

### ISSUE THREAD

**Issue by avijitsinha08** [hkamel/sonar-auth-aad#117]
Followed the steps as per MS documentation (Tutorial: Azure Active Directory single sign-on (SSO) integration with Sonarqube | Microsoft Docs) However, after authentication redirecting to http://localhost:9000/sessions/unauthorized .

Kindly assist if someone has the solution .

**Comment by level4complete** [comment]
Same here🤔

**Comment by srvrguy** [comment]
Please make sure you are following the guide in [this project's wiki](https://github.com/hkamel/sonar-auth-aad/wiki), not an external source. If you continue to have issues after reviewing all the steps there and have confirmed all the settings are correct, please respond and we'll try to troubleshoot.

**Comment by srvrguy** [comment]
This issue is old and hasn't had any activity. If the problem still exists, please open a new issue.
