### ISSUE TITLE
AAD settings in sonar.properties / Environment variables

### ISSUE THREAD

**Issue by extravio** [hkamel/sonar-auth-aad#118]
Hi there,
I've successfully set up the AAD in the GUI.
I then reset all the values to default and added the configuration in the sonar.properties file.
```
sonar.auth.aad.enabled=true
sonar.auth.aad.clientId.secured=***
sonar.auth.aad.clientSecret.secured=***
sonar.auth.aad.tenantId=***
sonar.auth.aad.allowUsersToSignUp=true
sonar.auth.aad.loginStrategy="Same as Azure AD login"

```
However, after I restarted SonarQube, the AAD login was not available any longer.
Am I missing something?

Another thing: I thought I could overwrite the settings with environment variables for example
sonar.auth.aad.clientSecret.secured => SONAR_AUTH_AAD_CLIENTSECRET_SECURED
It does not seem to work for "sonar.auth.add.*" variables. Is it correct?

**Comment by srvrguy** [comment]
The plugin uses the standard SonarQube settings functionality. Any special ways to set configuration outside the UI that are supported by SonarQube _should_ work, but these methods are not tested with this plugin. Also, I cannot tell you how it will work to have the settings in multiple locations, such as setting them in the UI _and_ other locations.

It seems that using the sonar.properties file for plugin configuration is not a supported scenario for SonarQube and behavior when doing that is undefined.
