### ISSUE TITLE
The plugin don't install

### ISSUE THREAD

**Issue by mbacab** [hkamel/sonar-auth-aad#119]
I have tried to install the plugin from SonarQube's marketplace. 

1. Searching the plugin by name
2. When appear, click on install button
3. Appear one message on the top of the windows notifying that the server is restarting
4. After the server restart, I tried to find the plugin again but don't appear on the installed tap

Reply all steps, but the result is the same

SonarQube Version : 8.9.2.46101

**Comment by srvrguy** [comment]
That's rather odd behavior. I'd suggest checking the plugins directory physically on the system and seeing if the extension JAR is in it. This would be under "extensions/plugins".

**Comment by srvrguy** [comment]
This issue is old and hasn't had any activity. If the problem still exists, please open a new issue.
