### ISSUE TITLE
Getting redirected to http instead of https

### ISSUE THREAD

**Issue by tuomastielinen** [hkamel/sonar-auth-aad#124]
I'm being redirected to http, not https after authenticating with Azure AD. Our server doesn't have port 80 open, so it times out. If I navigate to https-version of out sonarqube after that, I am logged in.

- Our SonarQube is Developer Edition Version 9.1 (build 47736)
- Azure Active Directory (AAD) Authentication Plug-in for SonarQube is version 1.2.0

We use nginx reverse proxy. It's config is:
```
server {
    listen 443 ssl;
    server_name sonar.domain.com;
 
    ssl_certificate /etc/pki/nginx/sonar.domain.com.crt;
    ssl_certificate_key /etc/pki/nginx/private/sonar.domain.com.key;
 
    access_log /var/log/nginx/sonarqube.access.log;
    error_log /var/log/nginx/sonarqube.error.log;
 
    proxy_buffers 16 64k;
    proxy_buffer_size 128k;
 
    location / {
 
        # Redirect to Sonar
        # Same IP as set in "sonar.web.host"
        proxy_pass http://192.168.41.82:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
 
    }
}
```

I have set Server base URL in Configuration --> General to `https://sonar.domain.com`.

In Azure I have set Redirect URI to `https://sonar.domain.com/oauth2/callback/aad`.

When I log into Azure AD, I get the correct redirect_uri: `redirect_uri=https://sonar.domain.com/oauth2/callback/aad` in URL. After the timeout I'm left with `http://sonar.domain.com/#` in the address bar.

**Comment by srvrguy** [comment]
That is very odd. Normally that setup should work fine. Especially if the passed redirect_uri parameter is the correct HTTPS version.

I'd suggest tracing the login process in a browser. Pop open developer tools, go to the network tab, and make sure to check the box to preserve the logs between sites. After you get kicked to login.microsoft.com, you should see a call to your redirect uri with several parameters like code, session_state, and state. That should have created a few cookies and done a 302 redirect to "/". Let me know if you see the same behavior.

Also, this is how I have my Nginx proxy set up for the site. Some of it may be unnecessary, but it's been working for me for quite some time. The last two header lines are for managing websockets, and those parameters are set up in a map in a different area. You can probably ignore those.:
```
server {
    listen 443       ssl http2;
    listen [::]:443  ssl http2;
    server_name      sonar.example.com;

    ssl_certificate     /path/to/cert.pem;
    ssl_certificate_key /path/to/key.pem;

    # Allow larger file transfers
    client_max_body_size 0;

    # Don't buffer requests or responses
    proxy_request_buffering off;
    proxy_buffering off;

    access_log /var/log/nginx/sonarqube.access.log;
    error_log  /var/log/nginx/sonarqube.error.log;

    location / {
        proxy_pass          http://localhost:9000/;
        proxy_http_version  1.1;
        proxy_set_header    X-Forwarded-For $remote_addr;
        proxy_set_header    Host $server_name:$server_port;
        proxy_set_header    X-Forwarded-Host $http_host;    # for CSRF check
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection $connection_upgrade;
    }
}
```

**Comment by tuomastielinen** [comment]
Okay, looks like it was a problem with my Nginx configuration. I tested with your configuration, minus the last two lines, and it works like it should. 

Thanks for your help.
