### ISSUE TITLE
 Azure AD for authentication Issue 

### ISSUE THREAD

**Issue by Jefinreji19** [hkamel/sonar-auth-aad#125]
We are trying to use Azure AD for authentication. We've setup everything according to documentation, however, AD authentication return the error message that says
 "The page you were looking for does not exist.
You may have mistyped the address or the page may have moved.
Go back to the homepage"

![image](https://user-images.githubusercontent.com/79885490/147704070-c9388b78-3bc1-4869-bc2b-464c76a9500f.png)

Can you please help us to resolve the issue?

**Comment by srvrguy** [comment]
It looks like you're not being redirected to the MS login page. Are you using IIS as a reverse proxy? If so, check the troubleshooting item under the header [I'm never getting sent to the Microsoft login page](https://github.com/hkamel/sonar-auth-aad/wiki/Troubleshooting#im-never-getting-sent-to-the-microsoft-login-page).

**Comment by Jefinreji19** [comment]
Yes, I am using the IIS as a reverse proxy. 

Here is the IIS screenshot that I have configured.
![image](https://user-images.githubusercontent.com/79885490/147771220-5bee8c57-e503-4223-86a6-d6c9c0d3f04e.png)

AD configuration

![image](https://user-images.githubusercontent.com/79885490/147771423-4646cb84-8753-4638-a0b6-0f5486ed369f.png)
![image](https://user-images.githubusercontent.com/79885490/147771511-c049faba-7eb8-46f3-9eb6-534ab7806578.png)

Would you please check the above screenshot and let me know the issue?.

**Comment by srvrguy** [comment]
The setting you need to change is not available in the web.config. It is a server-level change. If you can use IIS Manager, follow the steps at the troubleshooting item.

If you can't use that, but can run the `appcmd.exe` executable under `%windir%\system32\inetsrv`, then you can run the following command when in that directory in PowerShell or Command:

```appcmd.exe set config -section:system.webServer/proxy -reverseRewriteHostInResponseHeaders:false```

If neither of those are possible, you could try editing the IIS config files directly. I do not recommend this, as it's easy to break the config enough that IIS will not work properly. You will want to edit the file named `applicationHost.config` that lives in `%windir%\system32\inetsrv\Config` and is an XML file. You'll need to find the `system.webServer` section and look for the "proxy" tag. If it doesn't exist, then you can create it. You want to add or edit an attribute named "reverseRewriteHostInResponseHeaders" and have it use the value "false", similar to the following line:

```<proxy enabled="true" reverseRewriteHostInResponseHeaders="false" />```

I am not sure if IIS will pick up a manual edit, so you may need to restart the IIS service. I highly advise either using the IIS Manager method or at worst the appcmd.exe method. If you must do the manual edit, back up the entire IIS config directory before making any changes.

**Comment by Jefinreji19** [comment]
Thank you for your help. I was able to resolve the above issue and now I'm running into a different issue. Getting an error message that says "You're not authorized to access this page. Please contact the administrator."
Can you please see the screenshot and suggest to me what needs to be done. 

![image](https://user-images.githubusercontent.com/79885490/148269718-9325442f-3df5-4190-a479-9f4cb4b0e477.png)

**Comment by srvrguy** [comment]
So, the problem is that you already have local accounts on the server. SonarQube really doesn't like having duplicate e-mails. In the plugin settings, what do you have "Login generation strategy" set to?

Also, you may want to pull that image you posted. It has user e-mails displaying in it and that might be a bit of an info leakage issue for your org.

**Comment by Jefinreji19** [comment]
Where can we find the login generation strategy?

**Comment by Jefinreji19** [comment]
Can you please let me know when do I find the login generation strategy? we are facing an issue with our products as well.

**Comment by Jefinreji19** [comment]
2022.01.10 01:43:23 ERROR web[AX4YKLPV7BK2h+i5AHoy][o.a.a.a.AadIdentityProvider] Exception:java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS7000222: The provided client secret keys are expired. Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https:\/\/docs.microsoft.com\/azure\/active-directory\/develop\/active-directory-certificate-credentials\r\nTrace ID: 719a557e-64aa-4534-abfd-6a99a74e2f02\r\nCorrelation ID: 01eeec3d-5719-420c-830b-e5e04143e335\r\nTimestamp: 2022-01-10 07:43:23Z","error":"invalid_client","error_uri":"https:\/\/login.microsoftonline.com\/error?code=7000222"}
2022.01.10 01:43:25 INFO  web[][c.m.a.a.AuthenticationAuthority] [Correlation ID: a35be365-b68e-4eba-bcd4-4f9a32cc575c] Instance discovery was successful
2022.01.10 01:43:25 ERROR web[][c.m.a.a.AuthenticationContext] [Correlation ID: a35be365-b68e-4eba-bcd4-4f9a32cc575c] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.
com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS7000222: The provided client secret keys are expired. Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https:\/\/docs.microsoft.com\/azure\/active-directory\/develop\/active-directory-certificate-credentials\r\nTrace ID: 74e0390d-a3a8-4716-8545-6579ccf72f02\r\nCorrelation ID: a35be365-b68e-4eba-bcd4-4f9a32cc575c\r\nTimestamp: 2022-01-10 07:43:25Z","error":"invalid_client","error_uri":"https:\/\/login.microsoftonline.com\/error?code=7000222"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:128)

**Comment by srvrguy** [comment]
Based on a message you had previously sent but deleted, I think the error log you posted showed at least one major issue, and that your client secret expired. If that's expired, any login will fail. You can generate a new client secret in the Azure portal.

As for where to find the login generation, that's in the SonarQube admin area under General Settings -> Azure Active Directory -> Login generation strategy. All the plugin configuration settings are in this area, so if you ever need to find a different setting, look there.

**Comment by srvrguy** [comment]
This issue is old and hasn't had any activity. If the problem still exists, please open a new issue.
