### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by gravufo** [hkamel/sonar-auth-aad#126]
The Wiki's group sync section seems to mention that nested membership is not supported:
`The plugin doesn't work with indirect group membership, such as when a group is a member of another group.`

That said, looking through the old issues, I noticed this commit: https://github.com/hkamel/sonar-auth-aad/commit/84bb72b8026f1305bef5bbd6b3033aa8ca04e02d

So my question is: Does the plugin supported nested groups/transitive membership or not?

Also, it would be great if the doc is updated to mention the proper permission request rather than `Directory.AccessAsUser.All`. As stated in issue #103 the plugin works with only `Directory.Read.All`.

Thanks

**Comment by srvrguy** [comment]
Yes, nested membership is supported. The documentation needs to be updated for that. I had planned on updating after the next release, but I may do before.

Additionally, `Directory.AccessAsUser.All` should work just fine, [based on the documentation Microsoft provides](https://docs.microsoft.com/en-us/graph/api/user-list-transitivememberof) for the API endpoint the plugin uses. My legacy setup uses that permission and it works quite fine. It might be better to use `Directory.Read.All` for new setups as it is less privileged. I can certainly update the docs to mention this and provide the link there.

**Comment by gravufo** [comment]
Thanks a lot for the quick answer! Very glad the nested membership is supported! :)

Feel free to close this issue if you wish, unless you want to keep it to track the Wiki documentation changes.

Thanks again.

**Comment by gravufo** [comment]
Closing this issue since it has been answered.
