### ISSUE TITLE
Question: Is this project still maintained? 

### ISSUE THREAD

**Issue by Breee** [hkamel/sonar-auth-aad#128]
Greetings, 

as the last commit was on 27 Oct 2021, I am wondering if this plugin is still maintained 

Kind Regards
Bree

**Comment by srvrguy** [comment]
This plugin is still somewhat maintained. I have been a bit busy with some projects at my normal job and haven't had too much of a chance to work on things. The good news is that the plugin is mostly stable and works at least up to SQ 9.2 by my testing. I haven't had a chance to test with 9.3 yet, but I don't see anything that would block it from working.

The main target for future development would be to remove the ADAL library and replace with either MSAL or maybe Scribe, as we don't need any of the advanced features in the more complex MSAL library. I have some work on that process on my personal testing fork. I also have some work I landed in develop to clean up and organize the settings for the plugin. Additionally, the Azure Germany isolated cloud would need to be removed from the settings as Microsoft discontinued that isolated region in favor of data centers on the general/global cloud.
