### ISSUE TITLE
[o.a.a.a.AadIdentityProvider] Exception:java.lang.IllegalArgumentException: Group name cannot be empty

### ISSUE THREAD

**Issue by simo222** [hkamel/sonar-auth-aad#134]
hi, 

since today we are not able to use SonarQube with azure active directory 
[AYGkm8KKysL888ePAAJa][o.a.a.a.AadIdentityProvider] Exception:java.lang.IllegalArgumentException: Group name cannot be empty

this our version
Community Edition: Version 7.9.1 (build 27448

this is the error we get 
![image](https://user-images.githubusercontent.com/50549804/175935520-1ab3198d-887d-499e-ac07-95b88efd27ac.png)

we have issue when group synchronization is on. 
![image](https://user-images.githubusercontent.com/50549804/175935286-17d15a02-85c9-4725-beb2-0fa12239efd4.png)

If I disable group synchornation, then we are able to login. however we need to add users manually to SonarQube. 
as a work around we are doing adding user manually to sonarQube . 
before doing upgrade of SonarQube, we would like to solve this issue. 
/opt/sonarqube/extensions/plugins/sonar-auth-aad-plugin-1.1.jar

By the way. I will try plugin 1.2. let's see if it help. any idea why suddenly azure AAD stopped working ?

**Comment by srvrguy** [comment]
Just wanting to follow up and see if the newer plugin version worked for you.
