### ISSUE TITLE
 Error  after login with Azure ad You're not authorized to access this page. Please contact the administrator.

### ISSUE THREAD

**Issue by TomH54321** [hkamel/sonar-auth-aad#136]
![image](https://user-images.githubusercontent.com/110875389/183551239-74dcd644-d191-483a-972a-a72048936b94.png)

![image](https://user-images.githubusercontent.com/110875389/183551421-df3ff0a0-e635-4d74-899c-5d615d8b9717.png)
![image](https://user-images.githubusercontent.com/110875389/183551506-8d134136-0b12-418a-a813-93ff144c486e.png)
![image](https://user-images.githubusercontent.com/110875389/183552015-ff3fe85a-8f24-462a-91a8-12e0f6e5a2f5.png)

![image](https://user-images.githubusercontent.com/110875389/183551789-80a12a95-cdb5-49ff-900b-b35e55ff9b4a.png)

Tried both 1.2.0 and new version 1.3.1 have same error
Could you please advice?
Thank you very much

**Comment by TomH54321** [comment]
Checked log, Seems the user email in o365 is already in use with other user
will create new users to test

**Comment by srvrguy** [comment]
@TomH54321, since your initial post showed the client secret, please re-generate the secret and disuse the one you were using.

**Comment by TomH54321** [comment]
Dear Michael,
Secret  updated, thanks for the reminder
