### ISSUE TITLE
Group not getting set

### ISSUE THREAD

**Issue by acrane1** [hkamel/sonar-auth-aad#139]
So I've installed the latest version of the plugin on 8.8 developer SonarQube. As far as I can see I've got everything setup correctly.
When I login in though, I'm getting assigned to the default group. 
I've checked in Azure the group name and membership is correct and matches the group name in SonarQube.
I've removed(deactivated) all users of SonarSube except the local admin.
I can login, but only get the default user, and I can't figure out why.
Screenshots to show all my configs.
Azure group members
![2022-10-14_133250](https://user-images.githubusercontent.com/6483954/195907296-b3bf9cf1-ecf2-4fcf-ab31-a83f7a12f43d.png)
Azure API Settings
![2022-10-14_132909](https://user-images.githubusercontent.com/6483954/195907306-3d952ae6-9e62-4640-9d00-d3e622a86235.png)
Azure Auth Settings:
![2022-10-14_132901](https://user-images.githubusercontent.com/6483954/195907307-02814797-3009-4f4d-a315-34fde8efb699.png)
SonarQube User list:
![2022-10-14_132821](https://user-images.githubusercontent.com/6483954/195907309-2c930bfe-8b79-46c8-bc2c-c4daa1184101.png)
SonarQube Group List:
![2022-10-14_132812](https://user-images.githubusercontent.com/6483954/195907310-3467d69f-4270-463e-bedc-7175569f52a1.png)
My account after logging to Sonarqube using Azure AD:
![2022-10-14_132656](https://user-images.githubusercontent.com/6483954/195907311-f27a3f31-1072-4b60-8cc6-2b896ef45fa2.png)
Helm Config:
![2022-10-14_132937](https://user-images.githubusercontent.com/6483954/195907305-a1aee4e4-9f8c-4432-ba2f-65515b862fd0.png)
Log File:
![2022-10-14_133044](https://user-images.githubusercontent.com/6483954/195907304-66711a21-ecb2-41ed-9856-66fd7d4daa23.png)

**Comment by srvrguy** [comment]
As a first step, I'd make sure that the config settings you have specified in your Helm config are actually showing in the SQ UI. I have not tested with K8s, so I can't say if your method works for the extension or not. The fact that you're able to login via AAD makes me think so, but it's always worth a quick visual inspection that the UI reflects the settings you want.

After that, check that you're getting a groups list back by increasing logging to the Debug level. This will make sure that the process that grabs the group list for the login is working properly. You can adjust the logging by editing the sonar.properties file and set 'sonar.log.level.web' to 'DEBUG'. The value is commented out by default in the file. After adjusting the log level, restart SQ and monitor the file web.log. What you should see for a successful run is something like the following:
```
2022.10.14 11:45:03 DEBUG web[XXXXx/cmriovncmoeir][o.s.s.a.UserRegistrarImpl] List of groups returned by the identity provider '[COMMA-SEPERATED-GROUP-LIST]
2022.10.14 11:45:03 DEBUG web[XXXXx/cmriovncmoeir][auth.event] login success [method|OAUTH2][provider|EXTERNAL|Microsoft][IP|127.0.0.1|XXX.XXX.XXX.XXX][login|internal-username]
```

If this looks different, the process is likely not working properly. If you do see something like the above, check that the group you want is in the group list shown in the logs. If everything looks good up to that point, then it's something going on internally and there will likely need to be some more intense debugging done to figure out what's failing.

**Comment by acrane1** [comment]
When I go to the UI I don't see anything configured under the azure active directory plugin. Though this was also the case when we were using SAML and configured it through HELM.
I checked the debug logs and searching for "UserRegistrarImpl" reveals nothing, but I do have lines showing my login.
Multiple users have been able to login using the plugin, but all get the default group.
2022.10.14 19:12:46 DEBUG web[AYPXVcBbmHT0EF/EAAj/][auth.event] login success [method|OAUTH2][provider|EXTERNAL|Microsoft][IP|10.0.210.153|10.0.210.62][login|adam-crane72158]

**Comment by acrane1** [comment]
fixed the issue, it was a typo in the helm config. 
sonar.auth.aad.enableGroupsSync: true
