### ISSUE TITLE
Cannot authorize Azure app

### ISSUE THREAD

**Issue by kristiannikolaev** [hkamel/sonar-auth-aad#145]
Hi, I did everything on the setup wiki page. The issue comes at the first login, I must authorize the Azure application using my credentials and when I do it, I get the following error:

`The redirect URI 'http://localhost:9000/oauth2/callback/aad' specified in the request does not match the redirect URIs configured for the application 'e02e188b-8622-4f11-8b60-393e908094ed'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal.`

How can I change that localhost URL?

I've got sonarqube running on a docker-compose, I can share it if needed.
![sonarqube-error](https://user-images.githubusercontent.com/73645731/210398270-c95c3e7b-fa61-42bb-9aee-5aa2664908e0.JPG)

**Comment by srvrguy** [comment]
Have you made sure you set a value for the "Server base URL" in SonarQube itself? It's under Administration -> Configuration -> General (this is the default section if you just select "Administration" from the top bar in SQ). This setting overrides any auto-detected value, which is important if you're proxying the application or using it in a container.

**Comment by srvrguy** [comment]
Closing this issue for now as there has been no response.
