### ISSUE TITLE
group ad sync KO

### ISSUE THREAD

**Issue by cedrichelloasso** [hkamel/sonar-auth-aad#156]
plugin_version : 2.0.0
mode: The "Impersonation" Method

Hello,

We are using your extension for the sonar/azure AD link and thank you for doing so.
The authentication part works, but not the group assignment. We followed your wiki for the configuration but the groups associated with the users don't come up. In the Debug logs:
```
[o.a.a.a.AadUserInfo] Group list was empty. Maybe your AAD permissions aren't set correctly?
[o.s.s.a.UserRegistrarImpl] List of groups returned by the identity provider '[]'
```

We have set the **user.read** permission on Microsoft Graph.

by testing the endpoint graph with the **/transitiveMemberOf** parameter, the groups are displayed but the displayName is empty.

**Comment by cedrichelloasso** [comment]
I've found the solution, you need to add the **Directory.Read.All** right, and the display name goes back up. With this, the group synchro works.

**Comment by KevinDW-Fluxys** [comment]
For us it also works with the Group.Read.All permission
