### ISSUE TITLE
Guest users names appear as "null null"

### ISSUE THREAD

**Issue by kensykora** [hkamel/sonar-auth-aad#35]
SonarQube Version: 7.0.0.36138
sonar-auth-aad Version: 1.1-RC1

I have guest users in my Azure Active Directory. The users authenticate against the Primary AD but are guests in the Primary AD (however their accounts originate from a different azure tenant). We do not have multi-tenant enabled (should we?) - With the plugin enabled, when they log in, they show up as "null null". Normal users within the AD have their names set correctly. Wondering how this can be addressed?

Is there a way I can share the token with you somehow so you can inspect the claims to see what's going on?

**Comment by kensykora** [comment]
I can manually change their name in SonarQube, but the next time that they log in, their name is reset back to "null null"

**Comment by hkamel** [comment]
Thanks @kensykora will look into this

**Comment by hkamel** [comment]
@kensykora I tried the same scenario by inviting a guest user (@hotmail) to my tenant and I'm able to see the right profile information.

Could you please make sure the guest user profile information (first name and family name) are set? those are the values we relay on to display the right user information.

**Comment by kensykora** [comment]
That was the first thing I checked, and they were set correctly. The guest users are actually coming from another Azure AD Tenant which itself is configured to do single sign-on with an ADFS directory. I'm sure that I don't expect you to be able to fully support this, but wondering if there's a way that I can capture the claims coming back to send to you for investigation?

**Comment by hkamel** [comment]
@kensykora the claim sent by AAD in case of a guest user may various depend on the application manifest and the information sent in the claim. I'm working on a fix where we will rely on Display Name in case of First, family or given names are empty.

**Comment by tylersplitt** [comment]
All new users (not just guests) who log in with AAD are being created as `null null ` users. We have not yet updated to the new Release Candidate. The first user we saw with this was created Feb 20 of this year. Do we need to make changes on the Tenant side to resolve this?

**Comment by srvrguy** [comment]
I'm interested in knowing what's set up in the AD profile for these users. Can you go into the AD profile for one of the users and report back what you see for the Name, First Name, Last Name, and User type fields in the Identity section of the profile? You don't need to give actual real names, as I'm more interested in what fields are blank for the affected users and not for those that are working.

**Comment by tylersplitt** [comment]
It looks like their `First name` and `Last name` properties are empty but the `Name` has their name. Their `User type` field is `Guest` so I apologize for saying it was all new users in my above comment.

**Comment by srvrguy** [comment]
That makes sense then. When the account information is being generated, it sets the name as First + Last and ignores the "Name" property.

I'm thinking it might be better to use the "Name" property, and then fall back to the First + Last style if that's blank, and fall back to the "Displayable ID" as a last resort. Thoughts?

As for an AD-side fix for now, just make sure when you invite a guest, to fill out the First and Last name profile fields in their AD entry.

**Comment by mmajis** [comment]
I wrote a fix candidate for this. Please have a look at PR #64 

Thanks!

**Comment by srvrguy** [comment]
Fixed in PR #64
