### ISSUE TITLE
Client Secrets disclosed in web API

### ISSUE THREAD

**Issue by cpandya2909** [hkamel/sonar-auth-aad#61]
- Sonarqube Version: 7.4
- Plugin: sonar-auth-aad-plugin-1.1-RC2.jar

When calling "/api/settings/values" API **"sonar.auth.aad.clientId.secured" , "sonar.auth.aad.clientSecret.secured" and "sonar.auth.aad.tenantId"** are disclosed in clear text without any authentication required.

As this information is secret, it should not be disclosed without any authentication.

**Comment by julienlancelot** [comment]
Hi, 
This is a know issue/feature : https://jira.sonarsource.com/browse/SONAR-11512.
You need to remove 'Anyone' permission from 'Execute Analysis' in Global Permissions.
Regards

**Comment by srvrguy** [comment]
As of SonarQube version 9.1, this was fixed by having SQ just not return the raw values of secured settings. You can find some info at [SONAR-15338](https://sonarsource.atlassian.net/browse/SONAR-15338)
