### ISSUE TITLE
SonarQube Azure AD login does not place users in correct groups

### ISSUE THREAD

**Issue by ck147** [hkamel/sonar-auth-aad#62]
I have set up Azure AD authentication on my SonarQube server as well as the corresponding app registration listed in Azure AD. The problem I am facing is that when I try to authenticate to the SonarQube portal using my Azure login, it logs me into the portal but doesn't place my account in the correct group!

My account is placed in the "sonar-users" default group when it should be fed into the other group which is named exactly the same as the group listed in Azure AD (as per the SQ documentation). 

Has any one experienced any issues similar to this? If so, did you manage to resolve it?

**Comment by srvrguy** [comment]
Make sure you granted the right permissions so that SonarQube can access the user profiles. Check the readme for how to grant the right permissions. If that doesn't work, we can try a few other things.

Also, sonar-users is the default group for all users, and that is expected.

**Comment by roninlives** [comment]
having the same issue
names in AD are the same as the groups in Sonar Groups and the 3 permissions in AD are set

**Comment by srvrguy** [comment]
Are they not being put in any group at all other than the sonar-users (default) group, or are they being placed in the wrong groups?

**Comment by roninlives** [comment]
they are only be put in sonar-users.  we have 2 other groups we manage via AD those 2 groups are added to Sonarqube groups and the users that are logging in are not showing up in those groups only sonar-users

**Comment by srvrguy** [comment]
Okay. Sounds like a permissions issue. This should be fairly straightforward to remedy. I've been working on updated documentation, so try to follow these steps and see if they fix the issue:

### For the Azure Side

1. To begin, sign into the [Azure Management Portal](https://portal.azure.com/). (If you are using one of the "national cloud" Azure instances, log in using the correct portal URL for your country.)

2. Open the Azure Active Directory blade from the shortcut on the left, or if the shortcut is missing, search from the top of the page.

3. On the sidebar, under the Manage category, choose `App registrations` and then select the application you registered for SonarQube.

4. Click on the `Settings` button at the top of the screen and then select `Required permissions`. Select "Windows Azure Active Directory" from the list that appears. Make sure that "Read directory data" from the "Delegated Permissions" section is selected. Make sure to select `Save` to update the permissions.

5. Click on the `Grant permissions` button at the top of the previous pane. This will grant the permissions that you selected and allow the plugin to read the user's groups. This step _must_ be done or group sync will not work.

### For the SonarQube Side

1. Log into your SonarQube install with an account that has administrative permission.

2. Click on the `Administration` header at the top, then select the `Azure Active Directory` tab from the general settings area.

3. Toggle the setting labeled `Enable Groups Synchronization` to on/enabled to activate the plugin.

**Comment by roninlives** [comment]
still no luck
![screen shot 2019-02-28 at 9 15 37 am](https://user-images.githubusercontent.com/46829441/53572581-93c75680-3b39-11e9-990c-2a6f4038e9f1.png)

**Comment by srvrguy** [comment]
Ugh. Okay. Do you want to try troubleshooting this outside the issue flow by contacting me directly? Glad to help either way, but not a fan of back-and-forth support on GH issue topics.

**Comment by srvrguy** [comment]
Closing issue due to no further feedback.
