### ISSUE TITLE
Authorizing via Azure AD doesn't respect https "reply to url". It tries to redirect to http.

### ISSUE THREAD

**Issue by svscorp** [hkamel/sonar-auth-aad#63]
I have SonarQube 7.3, with installed plugin 1.0

Details and configurations are done, Sonar URL is `https` in the settings, Reply URL in Azure App Registration is pointing to right domain and `https`.

When I open https://domain.name, click Azure AD button:
- it redirects me to Azure Login
- In that URL I see the "reply_url" is correct: `https://domain.name/....`
- After authenticating is stuck for a while (in the bottom of the browser I see: opening "domain.name") and then it times out. In the browser the address is in http

@kawtar01

**Comment by srvrguy** [comment]
That's odd, but it usually means a setting is off somewhere. I'd double-check that the server base URL is set up correctly in SonarQube (Administration -> Configuration -> General). Also double-check that the Client ID and Key along with the Tenant ID are all correct. The usual problem you'll see is that of a mismatch between the authorized Redirect URIs in the app registration and the URI SonarQube generates.

**Comment by elduddz** [comment]
I think I have something similar if it needs a separate issue I might raise it.

We are using a reverse proxy to secure our site.

If we start at http://sonarqube.local/ and login with AAD every thing is fine we redirect back to https://sonarqube.local

if we start at https://sonarqube.local we get a message saying 
```
The page you were looking for does not exist.
You may have mistyped the address or the page may have moved.

Go back to the homepage
```
in the url I can identify a few things:
https://sonarqube.local/[tenant]/oauth2/authorize?client_id=[clientID]&response_type=code&redirect_uri=https://sonarqube.local/oauth2/callback/aad&state=rkk4fn7r9v067sinehsk2rtc4a&scope=openid

I am guessing the https://sonarqube.local/[tenant]/oauth2/authorize should be something more azure related?

**Comment by elduddz** [comment]
I am fixed, so my issue was that I have IIS serving the 80 and 443 traffic on a reverse proxy rewrite to localhost:9000 and it was rewriting login.microsoft.com to sonarqube.local.

on the default rule I changed the basic match from `(.*)` to `^(((?!oauth2/authorize).)*)$`. This then (hopefully) looks at the url and in the case where I can be sure it isn't looking for authorisation it will rewrite to "localhost:9000"

I then created a new 2nd rule with `(.*)` which then does a full redirect to `https://login.microsoft.com/{R:1}`

There is probably a more elegant way, but this works for now.

**Comment by gautamksr** [comment]
I have an issue with AAD authentication with SonarQube server host in IIS with urlrewite.

I can access the sonarqube https://52.178.8.140, this is my public static IP, and same url has set to serverbase url to sonarqube.

set redirecturls in AAD is https://52.178.8.140/oauth2/callback/aad

I have followed the instruction to IIS url rewrite. 
after click on login with Microsoft in sonarqube the url in browser is

https://52.178.8.140/sessions/new?return_to=%2Fb3acc06a-b1ea-4183-a4a8-350a885e6f85%2Foauth2%2Fauthorize%3Fclient_id%3D1afe1e78-2599-4b35-a46b-e63c5f8393f1%26response_type%3Dcode%26redirect_uri%3Dhttps%3A%2F%2F52.178.8.140%2Foauth2%2Fcallback%2Faad%26state%3Dh5dlharigcdnsr6nf5cllv51f4%26scope%3Dopenid

I am stuck and not able to find what to do, any help please

**Comment by elduddz** [comment]
@gautasmksr, you need to adjust your rules. This isn't an issue with this plugin, bit more the redirection pattern is not quite right. See my post(the one just above your issue) and make those changes. You will need 2 separate rules.

**Comment by srvrguy** [comment]
This issue is covered on the project wiki's troubleshooting page: https://github.com/hkamel/sonar-auth-aad/wiki/Troubleshooting#im-never-getting-sent-to-the-microsoft-login-page

**Comment by hasithamgh** [comment]
> I am fixed, so my issue was that I have IIS serving the 80 and 443 traffic on a reverse proxy rewrite to localhost:9000 and it was rewriting login.microsoft.com to sonarqube.local.
> 
> on the default rule I changed the basic match from `(.*)` to `^(((?!oauth2/authorize).)*)$`. This then (hopefully) looks at the url and in the case where I can be sure it isn't looking for authorisation it will rewrite to "localhost:9000"
> 
> I then created a new 2nd rule with `(.*)` which then does a full redirect to `https://login.microsoft.com/{R:1}`
> 
> There is probably a more elegant way, but this works for now.
> 
> looking at this, I dont think this is the same issue, so happy to have my comments redacted

@elduddz appreciate if you could share your web.config file content with the rewrite rules.
thanks
