### ISSUE TITLE
Sonarqube Switching to a user when they signin

### ISSUE THREAD

**Issue by Pbsteed** [hkamel/sonar-auth-aad#65]

**Comment by Pbsteed** [comment]
seeing a weird issue where when i authenticate it creates a profile for me. Then my teammate authenticates and my session becomes his and doesn't create his profile.

**Comment by srvrguy** [comment]
That is odd. I've personally not seen that behavior before. Does this happen with native accounts as well, or only with login via this plugin?

**Comment by Pbsteed** [comment]
Figured it out. It’s a byproduct of using the 1.0 plugin with the Docker version. It’s been resolved in 1.1. I will be closing this issue shortly.

**Comment by janvanveldhuizen** [comment]
I am facing this very issue today with my Docker container. In installed version 1.0 from the Marketplace menu. How do I upgrade to version 1.1?

**Comment by srvrguy** [comment]
To get the latest release of this plugin, go to the [releases section](https://github.com/hkamel/sonar-auth-aad/releases) on this project and download the jar file. With SQ not running, copy it into the plugins directory on your SonarQube installation and delete the old file. If you've set up the volume mapping correctly, this should be fairly easy to do. If you didn't set up a volume, you'll need to use the `docker cp` command to copy into the container.

**Comment by janvanveldhuizen** [comment]
Okay. Do I need to rename the jar file? Or just remove the 1.0 and replace it with the 1.1-RC2 version?

**Comment by janvanveldhuizen** [comment]
Thanks!
