### ISSUE TITLE
Sonar 7.7 Developer AAD

### ISSUE THREAD

**Issue by JayPowerUser** [hkamel/sonar-auth-aad#66]
We have enabled this with Azure Active directory it seems that only one person can have an account at a time, or be logged in at a time. 

After enabling, when testing with 2 users after user 1 logs in and then user 2 logs in user 2 is switched to user 1 profile. 

It seems as only one user can be logged in at a time. 

Is this supported for Sonar 7.7 Developer edition

**Comment by srvrguy** [comment]
What version of the plugin are you using? I know there were some issues with versions before the latest, 1.1 RC2.

**Comment by ColinM9991** [comment]
We have this issue also, only version 1.0 is available via the SonarQube marketplace and we'd rather use a production ready version instead of a release candidate which hasn't progressed since October 2018.

**Comment by srvrguy** [comment]
Versions prior to 1.1 RC2 break is odd ways on SonarQube 7.2 and newer due to how they used to treat one of the identifiers in the users table. I highly recommend switching to 1.1 RC2. It's stable and really the only thing keeping it from being pushed as 1.1 is getting all the qualifications in place to update it on the Marketplace.

**Comment by ColinM9991** [comment]
We've deployed RC and all works fine so happy to stick with that for now based on what you've said.

**Comment by hkamel** [comment]
@ColinM9991 we have multiple customers using 1.1 RC2 in production today. If you hit any other issue until we release, let us know.

**Comment by JayPowerUser** [comment]
@hkamel Great thanks for the feed back. I did notice that this is now working in 7.7 developer, but group sync is not working. We created 2 groups sonar-administrators and sonar-users, but sonar-administrators is not being assigned to based on the group membership. Any thoughts on this ?
