### ISSUE TITLE
New AD users overwrite an existing SonarQube user instead of creating a new one

### ISSUE THREAD

**Issue by Shtong** [hkamel/sonar-auth-aad#69]
Hello,

I just installed the plugin on a fresh SonarQube 7.7 setup. However its behavior is not as I expected: if two different persons connect to SonarQube using their respective AD logins, the second one will just override the first one's SonarQube user, instead of creating a new SonarQube user.

This makes things weird as if the first user is still connected, he'll be suddenly connected as the second one after the second one logged in (since the first user account is modified to contain the second person's info)

My configuration:
```
"sonar.auth.aad.clientId.secured": "xxxxxxxx",
"sonar.auth.aad.clientSecret.secured": "xxxxxxxx",
"sonar.auth.aad.enabled": "true",
"sonar.auth.aad.loginStrategy": "Unique",
"sonar.auth.aad.tenantId": "some guid",
```

Installed plugin:
```
{
  "name": "authaad",
  "version": "1.0"
}
```

I tried using the `Same as Azure AD login` generation strategy but it did not seem to fix this behavior

**Comment by srvrguy** [comment]
Install the 1.1 RC2 release from here. The 1.0 version isn't fully compatible with SonarQube 7.2 and newer.

**Comment by Shtong** [comment]
Thanks, the update fixed it.
