### ISSUE TITLE
Add new point about setting base URL in SQ settings to setup guide

### ISSUE THREAD

**Issue by ArveSystad** [hkamel/sonar-auth-aad#70]
Great guide! One thing I stumbled upon during setup, though, was the missing base URL in SonarQube. Maybe add a new point below "Configuring the Plugin in SonarQube", like the following:

6. Make sure you have set Server base URL under Settings/General to the root of the SonarQube installation _without a trailing slash_ (For example `http://sonarqube.yourdomain.com`).

**Comment by srvrguy** [comment]
When I was doing my testing, I didn't have any issues with the default, empty, value for that setting. Can you confirm that you had to set it to work properly for your install?

**Comment by ArveSystad** [comment]
Tried with a fresh install now, completely from scratch on a blank database. Filled in client id/secret etc - this gives you the login button, but it fails with an error when you reach the azure login screen. Adding the server base URL fixes this.

This was done with the 7.7-community image from docker hub.

**Comment by hkamel** [comment]
@ArveSystad thank you for your suggestion and for validating it. I have updated the wiki.
