### ISSUE TITLE
Plans for a release of 1.1?

### ISSUE THREAD

**Issue by colin-mueller-sonarsource** [hkamel/sonar-auth-aad#72]
Hello from SonarSource!

Are you planning on releasing an official version of _v1.1_ of sonar-auth-aad, and including it in the Marketplace? [An RFF was submitted to the community back in October](https://community.sonarsource.com/t/rff-azure-active-directory-aad-authentication-plug-in-for-sonarqube-1-1/3117), but no official release made. 

We recently decided to adjust the SonarQube 7.2 database migration when our _7.x LTS_ is released (target July 1st) to migrate the non-unique values in the dbo.users database table that causes a migration failure when a SonarQube instance using v1.0 of sonar-auth-aad is migrated to 7.2+ (see [SONAR-12120](https://jira.sonarsource.com/browse/SONAR-12120) for more details). An official release of sonar-auth-aad also compatible with our 7.x LTS would be a great pairing for our joint users. :)

Best regards,

Colin

**Comment by colin-mueller-sonarsource** [comment]
@srvrguy I just saw your comment here: https://github.com/hkamel/sonar-auth-aad/issues/55#issuecomment-493142775

Apologies! But likely you didn't know about the database migration on our side, so I hope that's some encouragement, and also a sign that we value your contribution to the SonarQube community.

**Comment by hkamel** [comment]
Thanks to @srvrguy, we have published release 1.1 and submitted the new release announcement https://community.sonarsource.com/t/new-release-azure-ad-authentication-for-sonarqube-plugin-1-1-0/10056
