### ISSUE TITLE
Azure Active directory authentication returlurl does not work

### ISSUE THREAD

**Issue by gautamksr** [hkamel/sonar-auth-aad#78]
I have an issue with AAD authentication with SonarQube server host in IIS with urlrewite (followed the instruction from https://jessehouwing.net/sonarqube-configure-ssl-on-windows/)

I can access the sonarqube https://52.178.8.140, this is my public static IP, and same url has set to serverbase url to sonarqube.

set redirecturls in AAD is https://52.178.8.140/oauth2/callback/aad

I have followed the instruction to IIS url rewrite. 
after click on login with Microsoft in sonarqube the url in browser is

https://52.178.8.140/sessions/new?return_to=%2Fb3acc06a-b1ea-4183-a4a8-350a885e6f85%2Foauth2%2Fauthorize%3Fclient_id%3D1afe1e78-2599-4b35-a46b-e63c5f8393f1%26response_type%3Dcode%26redirect_uri%3Dhttps%3A%2F%2F52.178.8.140%2Foauth2%2Fcallback%2Faad%26state%3Dh5dlharigcdnsr6nf5cllv51f4%26scope%3Dopenid

I am stuck and not able to find what to do, any help please

**Comment by gautamksr** [comment]
i have resolved this issues in IIS:
Make sure to turn off the checkbox “Reverse rewrite host in response headers” within the ARR (Application Request Routing) configuration of IIS. (Application Request Routing Cache --> Server Proxy Settings) 
reference: https://blogs.msdn.microsoft.com/visualstudioalmrangers/2016/06/04/running-sonarqube-behind-an-iis-reversed-proxy/

**Comment by srvrguy** [comment]
As a note, this is actually covered in our Wiki on the Troubleshooting page. https://github.com/hkamel/sonar-auth-aad/wiki/Troubleshooting#im-never-getting-sent-to-the-microsoft-login-page
