### ISSUE TITLE
Supporting groups inside of group and long Microsoft Graph responses

### ISSUE THREAD

**Issue by ericlemes** [hkamel/sonar-auth-aad#79]
Hi there,

Thank you very much for the great work in this plugin. It is being super useful for me.

Now, I'm trying to go one step further and use the group sync feature. I did setup and it is working fine, but I spotted 2 issues:

- Because you use the API /memberOf of Microsoft Graph, the plugin doesn't support nested groups. Just changing the API call to /transitiveMemberOf would do the trick. Any reason why you didn't make this choice?
- Because transitiveMemberOf can return a very long response, it will be paged. So, I noticed that the plugin doesn't follow the "@odata.nextLink" property in the response in order to fetch the full response.

Can you help with this?

**Comment by ericlemes** [comment]
BTW, I believe even with the /memberOf API, if the user is a member of a lot of groups in Azure AD, the plugin will sync only what's on the first page, which is probably a bug.

**Comment by ericlemes** [comment]
Hey @srvrguy, thanks for the reply.

Are you planning to fix the paging and/or the transitive group thing? Otherwise I could risk a PR...

**Comment by srvrguy** [comment]
You're welcome to contribute if you wish. I'm pretty slammed with my day job, so I probably won't get a chance to look into this for a bit.

**Comment by an-sush** [comment]
The pagination [fix](https://github.com/hkamel/sonar-auth-aad/issues/31) was made with this [pr](https://github.com/hkamel/sonar-auth-aad/pull/33)

However, a later [feature](https://github.com/hkamel/sonar-auth-aad/commit/d8dc93b77ccb8d41904697ba98672dda175d649a#diff-1f4964536f397e8679625954c7139bd6) seems to have broken it. The pagination attribute has changed from "odata.nextLink" (in graph.windows.net) to "@odata.nextLink" (graph.microsoft.com)

**Comment by srvrguy** [comment]
Thank you for that info. I'll see about making those changes as soon as I can.

**Comment by srvrguy** [comment]
Re-opening until the second half (transitive group membership) is resolved.
