### ISSUE TITLE
400 Bad Request when using nginx from redirect

### ISSUE THREAD

**Issue by tscrypter** [hkamel/sonar-auth-aad#83]
When running SonarQube behind an Nginx proxy with SSL offloading, I am able to authenticate against Azure AD; however, after the successful OAuth2 process, the user is ultimately redirected to `http://<server_host>:443` instead of `https://<server_host>`. This results in Nginx returning a `400 Bad Request: The plain HTTP request was sent to HTTPS port`. Per the [Nginx documentation](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl), the old way of configuring Nginx to allow this is no longer supported.

I have configured the reply URIs of my Azure application to be both HTTPS (done through UI) and HTTP (modify manifest directly). When the HTTP URI is used, the user is ultimately given a 403. When the HTTPS URI is used, the user is given the 400.

The current workaround is to have the app configured to use the HTTPS uri, then have the user remove the port at the end of the URL after the entire authentication workflow.

Details:
Ubuntu 18.04
Nginx 1.14.0
SonarQube 8.0

Nginx Config:
```nginx
server {
	listen 80;
	server_name hostname.com;
	return 301 https://hostname$request_uri;
}

server {
	listen 443 ssl http2;
	
	server_name hostname.com;
	
	ssl off;
	ssl_certificate /etc/letsencrypt/live/hostname/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/hostname/privkey.pem;
	
	location / {
	  proxy_set_header HOST $host:$server_port;
	  proxy_set_header X-Real-IP $remote_addr;
	  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
	  proxy_pass http://localhost:9000;
	}
}
```
Desired Behavior:  
After the user completes authentication, have the `https://hostname.com/oauth2/callback/aad?code=<code>&state=<state>&session_state=<session_state>` set the `location` header to `https://hostname.com` instead of `http://hostname.com:443`.

**Comment by tscrypter** [comment]
@hkamel I'm happy to make the changes and submit a PR to resolve this issue.

**Comment by srvrguy** [comment]
Is this a new issue with the SonarQube update? I've been running with nginx proxying things for some time without seeing this problem.

**Comment by tscrypter** [comment]
Found the problem, going to close the issue. It was a problem in my nginx config. specifically, the line `proxy_set_header HOST $host:$server_port;` has to be `proxy_set_header HOST $host;`. Apparently, when the host has a port specified, SonarQube will just use http://$host:$port, regardless of the fact that the X-Forwarded-Proto is HTTPS.
