### ISSUE TITLE
Maximum number of groups returned from identifier

### ISSUE THREAD

**Issue by trylvis** [hkamel/sonar-auth-aad#84]
Hi,

I have a ad user that is member of more than 100 groups in AAD, but when I turn on debuglogging in the web.log, only 100 groups is returned. Do you know if this is a limit set in the auth-provider(AAD), or in the plugin?

Steps to reproduce: Add user to more than 100 groups, log in.

**Comment by srvrguy** [comment]
Paging for more than the default number of groups is currently broken (see #79). The next release will contain a fix. If you can't wait, you can build the code in the master branch, as the fix has already been integrated, or let me know and I can provide a custom build if it's critical.

**Comment by trylvis** [comment]
Thanks for the reply @srvrguy, do you have any plans on when the next release will be?

**Comment by srvrguy** [comment]
I'm considering posting a release candidate at some point in the next seven days, with a release in December if there are no major issues discovered.

**Comment by srvrguy** [comment]
I've published a release candidate that has the fixes in it. You can download it directly from the release page: https://github.com/hkamel/sonar-auth-aad/releases/tag/1.2.0-RC1

Note that it will not be published on the Marketplace listings until the final release of 1.2.0, so if you want the fixes, you will need to manually update from the link above.

**Comment by nk111** [comment]
@srvrguy this really saved us! We also had one single user where the group sync didn't work. Turned out this user really had a lot of groups assigned in AD. This really drove us nuts. Updating to 1.2 solved the issue!
