### ISSUE TITLE
Tag does not match version

### ISSUE THREAD

**Issue by liger1978** [hkamel/sonar-auth-aad#88]
The tag/release number is 1.1 but the actual version is 1.1.0. Please can you create GitHub release/tag that matches the actual full version number? When they do not match it prevents automation. Thanks!

**Comment by srvrguy** [comment]
Thanks for the feedback. I'm probably not going to re-issue the 1.1.0 release, but going forward starting with the next release, this will be done.

The next release is currently looking to happen this week or next depending on my schedule.
