### ISSUE TITLE
You're not authorized to access this page. Please contact the administrator. Home

### ISSUE THREAD

**Issue by vijaytayde123** [hkamel/sonar-auth-aad#91]
Getting error while login to SonarQube using Azure active directory

**Comment by IbrahimUmar** [comment]
I am getting the same error. I dont know how to do this correctly.

https://community.sonarsource.com/t/youre-not-authorized-to-access-this-page-please-contact-the-administrator-after-integrating-with-saml-active-directory/17600

**Comment by dzsibi** [comment]
My pull request (#94) addresses the same exception, you can try it if you like.

**Comment by srvrguy** [comment]
I just published [1.2.0 RC2](https://github.com/hkamel/sonar-auth-aad/releases/tag/1.2.0-RC2), which incorporates the fixes from #94. Please test and let me know if it resolves your issue.
