### ISSUE TITLE
Client Secret exposed in settings after save

### ISSUE THREAD

**Issue by dfar-io** [hkamel/sonar-auth-aad#93]
After saving the Client Secret for my service principal, the secret is exposed to any other administrators within the system.

The secret should be masked to keep the value a secret (matching the functionality provided in Azure).

<img width="776" alt="2020-01-09 11_46_42-General Settings - Administration" src="https://user-images.githubusercontent.com/564106/72087167-f9e24580-32d5-11ea-9ba5-ac682f266a8a.png">

**Comment by srvrguy** [comment]
You should use the Settings Encryption feature that's part of SonarQube if you want to mask the value from view. See [Settings Encryption in the Official Documentation](https://docs.sonarqube.org/latest/instance-administration/security/#header-6) for information on how to do that. Note that for step 4, you just need to copy the generated value to the configuration field.
