### ISSUE TITLE
The reply URL specified in the request does not match

### ISSUE THREAD

**Issue by agferronato** [hkamel/sonar-auth-aad#95]
Hi,
i configure the aad auth for sonar, but i have the problem

> AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'd1f76780-ba12-411c-96e9-e440c2b397dc'. 

I already cross-check the configs for the URL, i have the issue on 2 sonarqubes (i have one for lab and another for homologation).

I already here a lot about, if is a case-sensitive case like (https://www.koskila.net/how-to-fix-aadsts50011-reply-address-did-not-match-because-of-case-sensitivity/) but still the same.

When i try to access https://mysonarqube/oauth2/callback/aad 

I have the message:

![image](https://user-images.githubusercontent.com/34922289/74675235-e0b09c80-5191-11ea-90c2-6d2af9f44206.png)

The permission for api

![image](https://user-images.githubusercontent.com/34922289/74675500-79471c80-5192-11ea-8426-71298ccc7f88.png)

The URI for callback

![image](https://user-images.githubusercontent.com/34922289/74675662-c4f9c600-5192-11ea-877f-cfb8d73e50b2.png)

I check the client id, tenant id and the secret is correct

**Comment by agferronato** [comment]
i see this issue
https://github.com/hkamel/sonar-auth-aad/issues/92

setting the Key: sonar.core.serverBaseURL with the sonar value works fine.

**Comment by srvrguy** [comment]
The reminder to properly set that value will be coming in a future release.
