### ISSUE TITLE
Setup documentation not up to date

### ISSUE THREAD

**Issue by ataylor05** [hkamel/sonar-auth-aad#98]
The plugin setup documentation at https://github.com/hkamel/sonar-auth-aad/wiki/Setup is no longer accurate in the Azure AD UI.  Can the Wiki be updated with correct steps to take in Azure AD?

**Comment by srvrguy** [comment]
The Azure portal is constantly changing, unfortunately. I'll see about updating the instructions as soon as possible.

**Comment by srvrguy** [comment]
Since I had to set up things for a new client today, I took the opportunity to get the new setup process documented as well.
